language: python
python:
  - "3.6"

php:
  - 7.1
  
install:
  - pip install -r requirements-test.txt
  - python setup.py install

  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras
  
  - php-fpm -v

  - phpenv local 7.1.11
  - phpenv global 7.1.11
  
  - php-fpm -v
  
  
script:
  - pytest
